Fix spurious exception while running tests.
Due to a race condition between serve_forever and shutdown, test run
logs randomly contained this exception:

Exception in thread Thread-NNN (serve_forever):
Traceback (most recent call last):
  ...
ValueError: Invalid file descriptor: -1