Disable building C speedups on PyPy
Disable building the C speedups on PyPy since it does not implement
"creating contiguous readonly buffer from non-contiguous".  As a result,
the respective tests fail with e.g.:

    ======================================================================
    ERROR: test_apply_mask_non_contiguous_memoryview (tests.test_utils.SpeedupsTests) (data_in=<memory at 0x00007f452c3758f8>, mask=b'4321'
    )
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/portage/dev-python/websockets-10.2/work/websockets-10.2/tests/test_utils.py", line 61, in test_apply_mask_non_contiguous_memoryview
        result = self.apply_mask(data_in, mask)
      File "/tmp/portage/dev-python/websockets-10.2/work/websockets-10.2/tests/test_utils.py", line 91, in apply_mask
        return c_apply_mask(*args, **kwargs)
    NotImplementedError: creating contiguous readonly buffer from non-contiguous not implemented yet

However, I suspect this may also affect real life use.