Remove IPv6 host entries.
It's impossible to connect to ::1 in a Circle CI container because IPv6
networking isn't set up:

    OSError: [Errno 99] error while attempting to bind on address ('::1', 0, 0, 0): cannot assign requested address